version: "3.5"

networks:
  fuzzy-trader:
    name: fuzzy-trader

services:
  sql_server_dev:
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: mssql
    container_name: sql-server-dev-fuzzy-trader
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: yourStrong(@@Password12
    networks:
      - fuzzy-trader
